### ISSUE TITLE
fix: Nested templates doesn't work within a folder

### ISSUE THREAD

**Issue by gucci-quoci** [felangel/mason#535] opened 2022-10-06 15:34 UTC
**Description**
Creating a nested template inside a folder doesn't generate the partial content.

**Steps To Reproduce**
1. Create a new brick
2. Create a folder named hello inside __brick__
3. Create a {{~ header}} file with "# Test"
4. Create a HELLO.md file with {{> header }} and "Hello world"
Result:

"Hello world" 

My file tree:
├── __brick__
│   └── hello
│       ├── HELLO.md
│       └── {{~header }}
└── brick.yaml

**Expected Behavior**
The header will be generated properly.

**Comment by felangel** [comment] 2022-10-06 16:44
Hi @gucci-quoci 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/mason/issues/378 so I'm closing this but feel free to comment/upvote #378 👍

**Closed by felangel** 2022-10-06 16:44 UTC
Labels: bug
