### ISSUE TITLE
fix: command duplication (mason 0.0.1-dev.47)

### ISSUE THREAD

**Issue by eli1stark** [felangel/mason#122] opened 2021-09-12 11:55 UTC
**Description**
Mason duplicates every command on the Windows machine. 
But I have to notice that it works fine despite that issue.

**Steps To Reproduce**
1. Have Windows (I haven't tried on MacOS)
2. Have the latest mason installed
3. Execute commands as shown on the screenshot

**Expected Behavior**
```
PS C:\Apps\mason_bricks> mason init
✓ Initialized (0.0ms)
✓ Generated 3 file(s):
  C:\Apps\mason_bricks\mason.yaml (new)
  C:\Apps\mason_bricks\bricks/hello/brick.yaml (new)        
  C:\Apps\mason_bricks\bricks/hello/__brick__/HELLO.md (new)
PS C:\Apps\mason_bricks> mason get
✓ getting bricks (0.0ms)
PS C:\Apps\mason_bricks> mason list
hello - An example hello brick.
PS C:\Apps\mason_bricks> mason make hello
name: Eli
✓ Made brick hello (1.7ms)
✓ Generated 1 file(s):
  c:\apps\mason_bricks\HELLO.md (new)
PS C:\Apps\mason_bricks> 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/57593530/132986555-b3e6ef4a-1864-4e83-8b1c-2cd316abf52c.png)

**Comment by felangel** [comment] 2021-09-12 14:13
Hi @eli1stark 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/mason/issues/73. Closing for now but if you’re still having trouble feel free to leave a comment and I’m happy to continue the conversation 👍

**Closed by felangel** 2021-09-12 14:13 UTC
Labels: duplicate
