### ISSUE TITLE
fix: Permission denied on each command getting bricks from Repo

### ISSUE THREAD

**Issue by jahajduk-lealco** [felangel/mason#773] opened 2023-02-23 16:52 UTC
**Description**

I try to use my templates from a GitHub repo, and I got an error about permission in order to get the templates, generate files or save them.

**Steps To Reproduce**

1. Specify the template direction (`mason.yaml`)
2. Use the command `mason get` in my flutter project
3. I need to use `sudo mason get` to get the files properly
4. Also, after I got my templates using `sudo` before command, CLI throw another error when I try to make (`mason make xxx`) a template in my project.
5. Command only works using `sudo`. But after use `sudo` to make templates (`sudo make xxx`), file is not able to edit because needs permissions each time I try to save it in my project. 

**Expected Behavior**

I need to use commands when I got templates from GitHub, without using `sudo` permissions, in order to handle my templates properly.

**Screenshots**

_Templates specification in `mason.yaml`_

![image](https://user-images.githubusercontent.com/109767473/220974285-97524d4a-da83-44c3-8c20-2a69fc86744d.png)

_Error getting packages using `mason get`_

![image](https://user-images.githubusercontent.com/109767473/220972846-980028b8-f50d-45ac-b2f4-f7f1eca6cbb6.png)

_Error trying to create a template using `mason make xxx` (after got templates using `sudo mason get`)_

![image](https://user-images.githubusercontent.com/109767473/220973503-fb853004-0593-4cd2-9c96-25244f651b79.png)

_Error trying to save a file after create it using `sudo mason make xxx`_

![image](https://user-images.githubusercontent.com/109767473/220973630-0130b4c4-47b4-4a78-b01b-b00229f70eee.png)

**Additional Context**

I appreciate if someone already has this problem and how solved it 👍

**Comment by felangel** [comment] 2023-02-23 17:02
Hi @jahajduk-lealco 👋 
Thanks for opening an issue!

Mason using `git` internally so I'm guessing the repositories are private you're not authenticated with git. You can verify this by trying to `git clone <git-url>`. Let me know if that helps 👍

**Comment by jahajduk-lealco** [comment] 2023-02-23 19:33
Hi @felangel 

I tried `git clone` where I located my templates, and I have the right access to clone it.

**Comment by felangel** [comment] 2023-02-23 20:00
@jahajduk-lealco sorry I took a closer look and it seems like a different issue. I believe this should be resolved in the latest version of mason_cli. Can you please upgrade and re-test and let me know if the problem persists? Thanks!

**Comment by jahajduk-lealco** [comment] 2023-02-23 20:29
Nothing, problem happen even with latest version
<img width="1480" alt="Screenshot 2023-02-23 at 3 27 45 PM" src="https://user-images.githubusercontent.com/109767473/221022636-4a0bc6e3-242a-48b4-91e4-9d8c4a434a17.png">

**Comment by felangel** [comment] 2023-02-23 21:00
> Nothing @felangel , problem still happening even with latest version
> 
> <img alt="Screenshot 2023-02-23 at 3 27 45 PM" width="1480" src="https://user-images.githubusercontent.com/109767473/221022636-4a0bc6e3-242a-48b4-91e4-9d8c4a434a17.png">

Can you share your `mason.yaml` file so I can try to reproduce the issue? Thanks and sorry for the inconvenience!

**Comment by jahajduk-lealco** [comment] 2023-02-23 21:11
Sure, no problem, here is an example of the `mason.yaml` file

```dart
bricks:
  feature_template:
    git:
      url: https://github.com/lealco/flutter_leal_core.git
      ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
      path: mason/lib/bricks/feature_template
  repository_template:
    git:
      url: https://github.com/lealco/flutter_leal_core.git
      ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
      path: mason/lib/bricks/repository_template
  remote_service_template:
    git:
      url: https://github.com/lealco/flutter_leal_core.git
      ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
      path: mason/lib/bricks/remote_service_template
  entity_template:
    git:
      url: https://github.com/lealco/flutter_leal_core.git
      ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
      path: mason/lib/bricks/entity_template
```

**Comment by felangel** [comment] 2023-02-25 18:54
> Sure, no problem, here is an example of the `mason.yaml` file
> 
> ```dart
> bricks:
>   feature_template:
>     git:
>       url: https://github.com/lealco/flutter_leal_core.git
>       ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
>       path: mason/lib/bricks/feature_template
>   repository_template:
>     git:
>       url: https://github.com/lealco/flutter_leal_core.git
>       ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
>       path: mason/lib/bricks/repository_template
>   remote_service_template:
>     git:
>       url: https://github.com/lealco/flutter_leal_core.git
>       ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
>       path: mason/lib/bricks/remote_service_template
>   entity_template:
>     git:
>       url: https://github.com/lealco/flutter_leal_core.git
>       ref: feat-jahajduk-lealco-flutter-leal-app-mason-bricks
>       path: mason/lib/bricks/entity_template
> ```

Is there any way you could provide a reproduction sample that consists of publicly available repos so that I can try to reproduce? It looks like the repositories you included above are all private so I'm not able to reproduce the issue locally :(

**Comment by felangel** [comment] 2023-05-25 03:31
Closing for now since there are no actionable next steps. Please provide a link to a minimal reproduction sample with public bricks and I'm more than happy to take a closer look, thanks!

**Closed by felangel** 2023-05-25 03:31 UTC
Labels: question, waiting for response
