### ISSUE TITLE
Got error in hooks while importing package

### ISSUE THREAD

**Issue by yhhCh405** [felangel/mason#525] opened 2022-09-23 04:17 UTC
I got runtime error while using methods from imported libraries. Is it not supported?
In pre_gen.dart

<img width="791" alt="Screen Shot 2022-09-23 at 10 42 39 AM" src="https://user-images.githubusercontent.com/26477761/191891198-448b38d4-6500-4cfa-b966-db9b01c66730.png">

_dart io in screenshot_

**Comment by felangel** [comment] 2022-09-23 04:52
Hi @yhhCh405 👋
That should be totally fine. Can you please provide a link to a minimal reproduction sample?

**Comment by yhhCh405** [comment] 2022-09-23 06:54
Steps to reproduce:
1. Clone this repo: [https://github.com/yhhCh405/demo_mason_bug](https://github.com/yhhCh405/demo_mason_bug)
2. Run `flutter pub get`
3. Run `cd mason && mason get && mason make prehooktest`          
And you will see error                       
<img width="341" alt="Screen Shot 2022-09-23 at 1 24 42 PM" src="https://user-images.githubusercontent.com/26477761/191906622-fe2f0624-f308-4ecb-8870-f531bb3c86f2.png">

**Comment by felangel** [comment] 2022-09-23 07:12
Thanks for the reproduction sample! I've narrowed down the issue to the fact that the path you're passing is invalid. If you change the `pre_gen.dart` script to the following, it runs without errors:

```dart
import 'dart:io';

import 'package:mason/mason.dart';

List<File> _flist = [];

void run(HookContext context) {
  context.logger.info("Pre gen running...");
  innerListLoop(Directory.current.path);
  print(_flist);
}

void innerListLoop(String path) {
  final entList = Directory(path).listSync();
  for (var fileEntity in entList) {
    if (fileEntity.statSync().type == FileSystemEntityType.file &&
        fileEntity.path.endsWith(".dart")) {
      _flist.add(File(fileEntity.path));
    } else if (fileEntity.statSync().type == FileSystemEntityType.directory) {
      innerListLoop(fileEntity.path);
    }
  }
}
```

I'm looking into why the current error is being reported since it is misleading.

**Comment by felangel** [comment] 2022-12-07 00:28
Closing since it doesn’t look related to mason. This appears to be an issue with how the error is reported for the current Isolate in Dart.

**Closed by felangel** 2022-12-07 00:28 UTC
Labels: bug, investigating
