### ISSUE TITLE
fix: Postgen hook fails with error

### ISSUE THREAD

**Issue by vasilich6107** [felangel/mason#1065] opened 2023-09-14 13:13 UTC
✗ Info: Compiling with sound null safety.
../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.1/lib/src/version_constraint.dart:96:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
 (2.9s)
✗ Making reactive_forms_widget_package (58ms)
Unable to compile hook: /Users/vasilich/IdeaProjects/reactive_forms_widgets/packages/reactive_forms_widget_package/hooks/post_gen.dart.
Error: Info: Compiling with sound null safety.
../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.1/lib/src/version_constraint.dart:96:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^

**Comment by chuong-pivot** [comment] 2023-09-15 06:24
+1 i have the same error
```
Unable to compile hook: /Users/closvil/code/projects/pvt_flutter_code_lab/init_proj/hooks/pre_gen.dart.
Error: ../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/mason.dart:7:1: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/mason_logger-0.2.7/lib/mason_logger.dart': No such file or directory
export 'package:mason_logger/mason_logger.dart';
^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/bricks_json.dart:5:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/http-1.1.0/lib/http.dart': No such file or directory
import 'package:http/http.dart' as http;
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:10:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/http-1.1.0/lib/http.dart': No such file or directory
import 'package:http/http.dart' as http;
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/mason_bundle.dart:4:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/archive-3.3.7/lib/archive.dart': No such file or directory
import 'package:archive/archive.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:216:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:338:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:418:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:165:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:185:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:202:25: Error: Type 'Logger' not found.
  Future<void> compile({Logger? logger}) async {
  ```

**Comment by felangel** [comment] 2023-09-15 13:05
Can you share what version of Dart you have installed on your machine? Also does the issue persist after you clear your mason cache via `mason cache clear`?

**Comment by chuong-pivot** [comment] 2023-09-18 01:39
@felangel Sorry for late response, yes the issue did persist after i run `mason cache clear` 
```
closvil@CHUONGCH-MacBookPro pvt_flutter_code_lab % mason cache clear
PathAccessException: Cannot open file, path = '/Users/closvil/.zshrc' (OS Error: Permission denied, errno = 13)
✓ Cache cleared (1ms)
closvil@CHUONGCH-MacBookPro pvt_flutter_code_lab % mason get 
PathAccessException: Cannot open file, path = '/Users/closvil/.zshrc' (OS Error: Permission denied, errno = 13)
✗ Getting bricks (2.5s)
Unable to compile hook: /Users/closvil/code/projects/pvt_flutter_code_lab/feature/hooks/post_gen.dart.
Error: ../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/mason.dart:7:1: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/mason_logger-0.2.7/lib/mason_logger.dart': No such file or directory
export 'package:mason_logger/mason_logger.dart';
^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/bricks_json.dart:5:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/http-1.1.0/lib/http.dart': No such file or directory
import 'package:http/http.dart' as http;
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:10:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/http-1.1.0/lib/http.dart': No such file or directory
import 'package:http/http.dart' as http;
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/mason_bundle.dart:4:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/archive-3.3.7/lib/archive.dart': No such file or directory
import 'package:archive/archive.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:216:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:338:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:418:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:165:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:185:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:202:25: Error: Type 'Logger' not found.
  Future<void> compile({Logger? logger}) async {
                        ^^^^^^
```

My dart version `dart --version`:
```Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_arm64"```

`flutter doctor`:
```
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by chuong-pivot** [comment] 2023-09-19 01:50
So i found out that i was running `dart pub global activate mason` instead of `dart pub global activate mason_cli`
so i'm sorry 🙏 But after i run the correct cmd, there's different bug logged:

```
closvil@CHUONGCH-MacBookPro pvt_flutter_code_lab % mason make auth_repo -c ./auth_repo/vars.json -o ../
PathAccessException: Cannot open file, path = '/Users/closvil/.zshrc' (OS Error: Permission denied, errno = 13)
✗ ../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/mason.dart:7:1: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/mason_logger-0.2.7/lib/mason_logger.dart': No such file or directory
export 'package:mason_logger/mason_logger.dart';
^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/brick_yaml.dart:4:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/meta-1.9.1/lib/meta.dart': No such file or directory
import 'package:meta/meta.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/bricks_json.dart:8:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/meta-1.9.1/lib/meta.dart': No such file or directory
import 'package:meta/meta.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:12:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/meta-1.9.1/lib/meta.dart': No such file or directory
import 'package:meta/meta.dart';
       ^
../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.4/lib/src/version.dart:8:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/meta-1.9.1/lib/meta.dart': No such file or directory
import 'package:meta/meta.dart' show sealed;
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:7:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/collection-1.17.2/lib/collection.dart': No such file or directory
import 'package:collection/collection.dart';
       ^
../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.4/lib/src/version.dart:7:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/collection-1.17.2/lib/collection.dart': No such file or directory
import 'package:collection/collection.dart';
       ^
../../../.pub-cache/hosted/pub.dev/pub_semver-2.1.4/lib/src/version_union.dart:5:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/collection-1.17.2/lib/collection.dart': No such file or directory
import 'package:collection/collection.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/mason_bundle.dart:4:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/archive-3.3.7/lib/archive.dart': No such file or directory
import 'package:archive/archive.dart';
       ^
../../../.pub-cache/hosted/pub.dev/http-1.1.0/lib/src/client.dart:9:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/meta-1.9.1/lib/meta.dart': No such file or directory
import 'package:meta/meta.dart';
```

Maybe because the mason_logger version using 2.7.0 and not 2.8.0, i think.

**Comment by felangel** [comment] 2023-09-19 03:06
> /Users/closvil/.zshrc

Thanks for replying! The new bug looks like a bug with the specific hook because it doesn't have permission to read the file `/Users/closvil/.zshrc`.

**Comment by chuong-pivot** [comment] 2023-09-19 07:04
I tried `sudo mason get` and still no clue, i also did `sudo mason cache clear` before get

```
closvil@CHUONGCH-MacBookPro pvt_flutter_code_lab % sudo mason get        
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
✗ Getting bricks (2.5s)
Unable to compile hook: /Users/closvil/code/projects/pvt_flutter_code_lab/local_config_repo/hooks/pre_gen.dart.
Error:    Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/mason.dart:7:1: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/mason_logger-0.2.7/lib/mason_logger.dart': No such file or directory
export 'package:mason_logger/mason_logger.dart';
^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/mason_bundle.dart:4:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/archive-3.3.7/lib/archive.dart': No such file or directory
import 'package:archive/archive.dart';
       ^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:216:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:338:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/generator.dart:418:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:165:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:185:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:202:25: Error: Type 'Logger' not found.
  Future<void> compile({Logger? logger}) async {
                        ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:250:50: Error: Type 'Logger' not found.
  Future<void> _compile({required HookFile hook, Logger? logger}) async {
                                                 ^^^^^^
../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/hooks.dart:280:5: Error: Type 'Logger' not found.
    Logger? logger,
    ^^^^^^
```

Should i open a new issue for this?

**Comment by felangel** [comment] 2023-09-22 04:26
@chuong-pivot yeah please open a new issue for this, I'm going to close this bug since there are no actionable steps to resolve the original issue as I'm not able to reproduce based on the comments and there hasn't been any follow up.

**Closed by felangel** 2023-09-22 04:26 UTC
Labels: bug, waiting for response
