### ISSUE TITLE
fix: Can't load Kernel binary: Invalid kernel binary format version

### ISSUE THREAD

**Issue by lukasz8k** [felangel/mason#1056] opened 2023-09-10 09:09 UTC
Hello,

I've started using Mason for my projects for a few days now, and I've noticed an error occurring with some of the bricks.

Recently, I have been using bricks: 

[https://brickhub.dev/bricks/hello/0.1.0+1](https://brickhub.dev/bricks/hello/0.1.0+1)
[https://brickhub.dev/bricks/model/0.7.1](https://brickhub.dev/bricks/model/0.7.1)
[https://brickhub.dev/bricks/app_ui/0.0.4](https://brickhub.dev/bricks/app_ui/0.0.4)

In the case of the `hello` brick it's works great, without any problems. When I try to use `model` or `app_ui` I get an exception:

```
✓ Compiled pre_gen.dart (3.0s)
An exception occurred while executing hook: .mason-cache/hosted/registry.brickhub.dev/app_ui_0.0.4/hooks/pre_gen.dart.
Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary format version.
```

I tried clearing cache, reinstalling but nothing helped.
Currently i am using mason 0.1.0-dev.50 installed via brew (m1 mac)

**Comment by felangel** [comment] 2023-09-13 00:59
Hi @lukasz8k 👋 
Thanks for opening an issue!

I'm not able to reproduce. Can you please provide detailed reproduction steps as well as what operating system you're using? Thanks!

**Comment by lukasz8k** [comment] 2023-09-14 18:17
Hi @felangel 

Sure no problem.
I currently use Apple M1 Max, operating system Ventura 13.5.2.

- I uninstalled Mason according to the instructions - [https://github.com/felangel/homebrew-mason](https://github.com/felangel/homebrew-mason)
- I reinstalled according to the same instructions as I linked above.
- I created a new flutter project
- in the terminal I used the command "mason init" with result:

> ✓ Generated 1 file. (17ms)
>   created mason.yaml

- At [https://brickhub.dev/bricks/model/0.7.1 ](https://brickhub.dev/bricks/model/0.7.1 ) ran the command "mason add model" with result

> ✓ Added model (1.0s)

- I then ran the command: _mason make model --model_name user --additionals "[copyWith, json, equatable]" --style basic with result:_

> ? SKIP THIS IF NOT USING A JSON FILE
> 
> ✓ Compiled pre_gen.dart (1.6s)
> n exception occurred while executing hook: /Users/user/.mason-cache/hosted/registry.brickhub.dev/model_0.7.1/hooks/pre_gen.dart.
> Error: Unable to spawn isolate: Can't load Kernel binary: Invalid SDK hash.

I have had such problems since the first installation of mason. Reinstalling doesn't help.  The problem does not occur with every brick.

For example:

[(https://brickhub.dev/bricks/greeting/0.1.0+2](https://brickhub.dev/bricks/greeting/0.1.0+2 ) works good:

>  ? What is your name? (Dash) ok
> ✓ Generated 1 file. (17ms)
>   created GREETINGS.md

[https://brickhub.dev/bricks/very_good_dart_package/0.4.0](https://brickhub.dev/bricks/very_good_dart_package/0.4.0) works good:


> ? What is the project name? (my_package) ok
> ? What is the project description? (A very good dart package) aaa
> ? Will the package be published? (y/N) No
> ✓ Generated 24 files. (0.1s)
>   created ok/test/src/ok_test.dart
>   created ok/README.md
>   created ok/coverage_badge.svg
>   created ok/pubspec.yaml
>   created ok/.gitignore
>   created ok/.github/cspell.json
>   created ok/.github/dependabot.yaml
>   created ok/.github/workflows/main.yaml
>   created ok/.github/PULL_REQUEST_TEMPLATE.md
>   created ok/.github/ISSUE_TEMPLATE/revert.md
>   created ok/.github/ISSUE_TEMPLATE/feature_request.md
>   created ok/.github/ISSUE_TEMPLATE/bug_report.md
>   created ok/.github/ISSUE_TEMPLATE/performance.md
>   created ok/.github/ISSUE_TEMPLATE/refactor.md
>   created ok/.github/ISSUE_TEMPLATE/style.md
>   created ok/.github/ISSUE_TEMPLATE/build.md
>   created ok/.github/ISSUE_TEMPLATE/chore.md
>   created ok/.github/ISSUE_TEMPLATE/config.yml
>   created ok/.github/ISSUE_TEMPLATE/documentation.md
>   created ok/.github/ISSUE_TEMPLATE/test.md
>   created ok/.github/ISSUE_TEMPLATE/ci.md
>   created ok/lib/ok.dart
>   created ok/lib/src/ok.dart


Last brick - [https://brickhub.dev/bricks/very_good_core/0.3.0](https://brickhub.dev/bricks/very_good_core/0.3.0) not working:

> mason make very_good_core
> ? What is the project name? (my_app) tt
> ? What is the organization name? (com.example) oop
> ? What is the application id? com.exa.eda
> ? What is the project description? (A Very Good App) qrt
> ✓ Compiled pre_gen.dart (1.3s)
> An exception occurred while executing hook: /Users/user/.mason-cache/hosted/registry.brickhub.dev/very_good_core_0.3.0/hooks/pre_gen.dart.
> Error: Unable to spawn isolate: Can't load Kernel binary: Invalid SDK hash.


Looks like after `Compiled pre_gen.dart ` I get an error.
I don't know much about what I can do about this error

**Comment by anasboyka** [comment] 2023-09-15 07:33
same here using mac mini with m1 chip..

**Comment by felangel** [comment] 2023-09-15 13:08
I’ll take a look later today in the meantime can you try uninstalling the homebrew mason_cli and reinstalling mason_cli from pub.dev `dart pub global activate mason_cli` and see if you’re able to reproduce?

**Comment by felangel** [comment] 2023-09-19 01:33
I tried to reproduce today and was not able using the following:
```
$ dart --version
Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_arm64"

$ mason --version
0.1.0-dev.51
```

If you're still having trouble, can you please let me know on [discord](https://discord.gg/bloc) and I'm happy to try to remotely debug the issue at your convenience, thanks!

**Comment by urvi-aecor** [comment] 2023-09-21 08:47
I'm experiencing the same problem when I try to create a new Mason brick using the mason new command with the --hooks flag. However, when I create a new brick without the --hooks flag, everything works perfectly fine.

**Comment by felangel** [comment] 2023-09-21 13:12
> I'm experiencing the same problem when I try to create a new Mason brick using the mason new command with the --hooks flag. However, when I create a new brick without the --hooks flag, everything works perfectly fine.

Can you provide more details around what version of mason_cli you’re using, what version of Dart you have installed, how did you install mason (pub or homebrew)? Thanks!

**Comment by felangel** [comment] 2023-09-22 04:27
Closing for now since I'm not able to reproduce. Feel free to provide additional context and/or a reproduction sample/steps and I'm happy to take a closer look 👍

**Closed by felangel** 2023-09-22 04:27 UTC
Labels: bug, waiting for response

**Comment by mrgnhnt96** [comment] 2024-01-15 23:26
@felangel Hey Felix! 👋 

I am able to reproduce this issue. I created a min reproducible example [here](https://github.com/mrgnhnt96/min_brick_example).

The root issue, as least for this case, comes down to running `flutter pub run` instead of `dart run`. Its more than likely that `mason` was never intended to run using `flutter pub`, so this might be more of a warning when `mason` was run using `flutter pub`,

**Comment by SAGARSURI** [comment] 2024-03-07 04:39
I am facing the same problem when running the following command:
```
mason make flutter_bloc_feature --name home --type bloc --style freezed
```

**Comment by felangel** [comment] 2024-03-07 05:34
> I am facing the same problem when running the following command:
> 
> ```
> mason make flutter_bloc_feature --name home --type bloc --style freezed
> ```
> 
> Error:
> 
> ```
> An exception occurred while executing hook: /Users/sagarsuri/.mason-cache/hosted/registry.brickhub.dev/flutter_bloc_feature_0.3.0/hooks/pre_gen.dart.
> Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary format version.
> ```

That likely means you updated to a newer version of Dart since you installed mason_cli and you just need to reactivate it `dart pub global activate mason_cli`. Hope that helps 👍

**Comment by SAGARSURI** [comment] 2024-03-07 07:15
But I have never installed `mason_cli`. I just installed it now and still getting the same error.

**Comment by felangel** [comment] 2024-03-07 14:11
> Yes I updated the version of Dart.
> 
> I tried `dart pub global deactivate mason` and reactivated it again. Still no luck I also deactivated `mason` and activated `mason_cli`. Still same issue

What version of Dart are you using (`dart --version`)? Also are you sure your path points to the version from pub or did you install using homebrew? (`which mason_cli`)

**Comment by SAGARSURI** [comment] 2024-03-08 04:42
Ah I see now! I installed mason using brew which caused this problem. After uninstalling and reinstalling with `dart pub`. It's working! Thanks @felangel
