### ISSUE TITLE
feat: Add output path to HookContext

### ISSUE THREAD

**Issue by vanlooverenkoen** [felangel/mason#448] opened 2022-07-12 09:56 UTC
**Description**

We want to remove files based on a boolean that was entered during config. But we don't have the output path available in HookContext.

**Requirements**

- [ ] Add output path to HookContext

**Comment by felangel** [comment] 2022-07-14 03:22
Hi @vanlooverenkoen 👋 
Thanks for opening an issue!

You can use `Directory.current` from `dart:io` within your hook to access the output directory. Let me know if that helps 👍

**Comment by vanlooverenkoen** [comment] 2022-07-14 09:30
That does not contain the output path if you use `-o custom/output/path` but only the location where mason was called

**Comment by felangel** [comment] 2022-07-14 12:42
> That does not contain the output path if you use `-o custom/output/path` but only the location where mason was called

The current directory of the hook should be the output directory. Can you share a minimal reproduction sample? Also, are you on the latest version of mason_cli?

**Comment by felangel** [comment] 2022-07-24 17:09
Closing for now since I believe this is working as expected and there are no actionable next steps.

**Closed by felangel** 2022-07-24 17:09 UTC
Labels: question, waiting for response

**Comment by vanlooverenkoen** [comment] 2022-07-25 07:57
We are using the latest mason cli. If I find time I will create a small example. (sorry I was on holiday)

**Comment by vanlooverenkoen** [comment] 2022-07-25 13:35
hmm strange in a minimal project it does work. 🤷 So no action needed for this ticket

**Comment by dungngminh** [comment] 2022-08-14 16:02
WYSI @vanlooverenkoen , the path when you defined in `-o foo_path` or `--output-dir foo_path`, you can get full path include `foo_path` you defined by `Directory.current`, if folder is not exist, it will create new folder first and `Directory.current` will have full path you defined.

This is my terminal and my mason:
``` sh
@dungngminh ➜ mason_projects git(master) -> mason make presentation_layer -o foo
? What is your Presentation Layer name? (Home) Home
? What is State Management you want to use cubit
{name: Home, stm: cubit}
Directory: '/media/dungngminh/Data/project/mason_projects/foo'
Do you want to use Equatable (Y/n) 
```
Sorry @felangel for opening this issue again.
