### ISSUE TITLE
feat: Add path dependencies to Hooks

### ISSUE THREAD

**Issue by vanlooverenkoen** [felangel/mason#449] opened 2022-07-12 09:57 UTC
**Description**

It is not possible to add a path dependency, I think the hooks pubspec will be resolved from the wrong location

`path: ../../` does not work when running from ../../ where the brick is located

**Requirements**

- [ ] Support for path dependencies

**Comment by felangel** [comment] 2022-07-23 03:36
Hi @vanlooverenkoen 👋 
Thanks for opening an issue!

This is a duplicate of #382.

**Closed by felangel** 2022-07-23 03:37 UTC
Labels: duplicate
