### ISSUE TITLE
feat: .brickignore

### ISSUE THREAD

**Issue by peter-gy** [felangel/mason#184] opened 2022-01-02 14:27 UTC
**Description**

When creating new bricks on a Mac, it is common that a `.DS_Store` file appears in the output, due to the fact that it is present somewhere in `__brick__`. It would be great to make it possible to specify files to be excluded from the templating. A section in `brick.yaml` could be dedicated for this, or support for a `.brickignore` file could be implemented.

Apart from the awesome feeling that one might get when pronouncing the file name `.brickignore`, it would also come with the benefit of being able to make use of the already familiar `.gitignore` syntax.

**Requirements**

- [ ] Make it possible to exclude files from the templating process

**Comment by felangel** [comment] 2022-01-02 16:04
Hi @peter-gy 👋
Thanks for opening an issue!

I believe this is a duplicate of #166. Let me know what you think, thanks!

**Comment by peter-gy** [comment] 2022-01-02 16:47
Hi @felangel,
Thanks for the swift response!

I do agree that this use case might not be worthy of any notable coding effort, as in most cases the user should be conscious about all the files lying in the `__brick__` dir. However, this is the problem with `.DS_Store`: users don't put it in the directory willingly, it is generated in the background as soon as we do some Finder navigation in the directory tree.

How do you see it, would it make sense to add some very basic support to exclude specific files? What I have on my mind is to have some sort of global configuration that the CLI can pick up.

On the other hand, it is not an extraordinary expectation from users to double-check their `__brick__` directory before generating code from them locally. Also, if users use bricks from a remote repository and they use `.gitignore` there, the issue I raised is rendered obsolete.

**Comment by felangel** [comment] 2022-01-05 05:41
Hey @peter-gy :wave

Sorry for the delayed reply!

I would really prefer to avoid this for now because as you mentioned it's trivial to remove any unwanted files from the `__brick__` directory and in most cases a `.gitignore` will take care of this for you.

In the future I'd consider adding a `.brickignore` if there is enough demand for it but I'm not convinced it's necessary at this point.

Closing for now but feel free to comment with any additional thoughts/comments/questions and I'm happy to continue the conversation, thanks! 🙏

**Closed by felangel** 2022-01-05 05:41 UTC
Labels: duplicate
