### ISSUE TITLE
logger.prompt with defaultValue if no input is provided, keeps waiting until we provide some input in Windows Powershell 

### ISSUE THREAD

**Issue by codesculpture** [felangel/mason#1214] opened 2024-01-11 18:14 UTC
Executing the below example would keep wait (forever) until u actually type something and hit enter making the defaultValue useless.

Since defaultValue should be replace with the `name` if there is no input received from `stdin`

This happens only on powershell (works fine on git bash)

Somehow, it keeping waiting forever until there is some input
```dart
import 'package:mason_logger/mason_logger.dart';

void main() {
  final logger = Logger();
  final name = logger.prompt(
    'Your Name',
    defaultValue: 'Cow',
  );
  print(name);
}

```

**Comment by felangel** [comment] 2024-01-11 18:18
Looks like a duplicate of #1189. Can we close?

**Comment by codesculpture** [comment] 2024-01-11 18:20
Sorry, dint noticed that. Yes can be closed.

**Closed** 2024-01-11 18:20 UTC
Labels: bug
