### ISSUE TITLE
feat: Copy empty directories in bricks

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#905] opened 2023-05-14 04:41 UTC
**Description**

I'd like to have the option to copy empty directories from bricks to the generated directory structure.

I have a brick that generates a new static website project for my end users. I'd like to include some empty directories in that project so that my end users have an easy onboarding process in terms of identifying where and how they might want to store various assets.

**Comment by felangel** [comment] 2023-05-14 04:54
Hey @matthew-carroll 👋
I believe this is a duplicate of #112

**Closed** 2023-05-14 05:00 UTC
Labels: duplicate
