### ISSUE TITLE
fix: Unable to sign in to GitHub for mason get

### ISSUE THREAD

**Issue by Fasuh** [felangel/mason#123] opened 2021-09-15 10:29 UTC
**Description**
when using a commant `mason get` the package is asking me to provide username and password, but as for now logging in to github with a password is disabled and we are getting an error.

**Steps To Reproduce**

1. add mason bricks to the private repo
2. run `mason get` on a clean install
3. try to log in to your GitHub account

**Expected Behavior**
i am unsure what should happen in this case, maybe provide steps to add an auth key

**Comment by felangel** [comment] 2021-09-16 14:29
Hi @Fasuh 👋 
Thanks for opening an issue!

I believe the issue is you probably cloned the github repo with ssh and the mason brick is using https or vice-versa. Can you please verify that you're providing the same git url as you're using to clone the repo? You shouldn't need to provide a password.

**Comment by felangel** [comment] 2021-09-23 14:48
Closing for now since there isn't enough information to take further action. Feel free to comment with additional questions/information and I'm happy to continue the conversation 👍

**Closed by felangel** 2021-09-23 14:48 UTC
Labels: question
