### ISSUE TITLE
fix: Issues on a mac running the "hooks" using mason bricks

### ISSUE THREAD

**Issue by nasreekar** [felangel/mason#432] opened 2022-06-27 01:34 UTC
**Description**

Error running the bricks with hooks on a mac. The same code is working perfectly fine on a windows machine. 

**Steps To Reproduce**

1. Generate a brick boilerplate template code with hooks using the `mason_cli` cmd 
`mason new <BRICK_NAME> --hooks
`
2. Make the necessary changes in the brick if needed and Run the brick using the `mason make` cmd
3. See an error (default hooks code except for the path in `mason.yaml` . )

**Expected Behavior**

The brick should be run without any error.  

**Screenshots**

<img width="1298" alt="Screenshot 2022-06-27 at 6 51 12 AM" src="https://user-images.githubusercontent.com/13792317/175843653-d95061cb-87a0-4588-983d-23ac186e8399.png">

<img width="823" alt="Screenshot 2022-06-27 at 6 57 25 AM" src="https://user-images.githubusercontent.com/13792317/175843767-68a23ca8-ed3f-4797-be4a-bca65daac340.png">

**Additional Context**

I'm adding the hooks to add some `pre_gen` and `post_gen` codes, which the brick might later use (for now, it's the default code generated using `mason new`. 

* The same code is working perfectly fine on a windows machine, whereas it is throwing the error mentioned above on a mac
* Upon removing the hooks and running the `mason make`, the code works perfectly alright on a mac, but it doesn't serve the purpose.  

Current versions:
```
Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (4 days ago) • 2022-06-22 11:34:49 -0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2
```
Mac Info:
```
macOS Monterey
version 12.4
```

**Comment by PandaTechMobile** [comment] 2022-06-27 05:07
+1 

Also facing this issue on mac m1.

**Comment by SHuygh** [comment] 2022-06-30 15:16
+1 Also facing the same issue.

**Comment by felangel** [comment] 2022-06-30 15:20
Can everyone who is experiencing this confirm that they are on an M1 Mac?

**Comment by SHuygh** [comment] 2022-06-30 16:06
I am not. I had the issue with my own brick and hooks, and got the same exception.
Currently, I don't have access to my Mac. I will run the brick from @nasreekar tomorrow morning 9am CET

**Comment by felangel** [comment] 2022-06-30 16:17
@SHuygh can you share a link to your own brick and hooks?

**Comment by SHuygh** [comment] 2022-07-01 11:15
It currently is not available online. But with the https://github.com/nasreekar/mason_bricks I get the same error.


`MacBook-Pro:mason-playground flowpilots$ mason make drift_crud
? What is the table name? (todo) test
Unable to execute hook: /Users/flowpilots/.mason-cache/git/mason_bricks_aHR0cHM6Ly9naXRodWIuY29tL25hc3JlZWthci9tYXNvbl9icmlja3M=_f60f41834b9ffea0bedab15e5601c7792217827c/bricks/drift_crud/hooks/pre_gen.dart.
Error: Unable to spawn isolate: The uri provided to `Isolate.spawnUri()` does not contain a valid AOT snapshot.`

Currently running on MacOs Monterey, Intel Core i9

**Comment by felangel** [comment] 2022-07-01 14:25
Thanks I’m looking into this and will report back later today, sorry for the inconvenience!

**Comment by felangel** [comment] 2022-07-07 04:48
@nasreekar @SHuygh the issue is when you install `mason` from homebrew. I'm working on a fix for this but in the meantime you should be able to uninstall from homebrew and install from `pub.dev`:

```
brew uninstall mason
dart pub global activate mason_cli
```

Let me know if that helps and sorry for the inconvenience!

**Comment by felangel** [comment] 2022-07-07 05:13
This should be resolved by https://github.com/felangel/homebrew-mason/commit/2f26bb06ba9345cc9b918c9e5c3969250a1ca7a1. You should be able to reinstall from homebrew and hooks should work properly. Let me know if you experience any difficulties and I'm happy to reopen this 👍

**Closed by felangel** 2022-07-07 05:13 UTC
Labels: bug

**Comment by nasreekar** [comment] 2022-07-08 01:59
@felangel I have tested it on my brick after reinstalling the mason via homebrew, and it works like a charm. No issues found. Thank you so much for picking it up and fixing it on priority :)
